In [6]:
!git clone https://github.com/Priya-96-aiml/ml-intern-assessment.git
%cd "ml-intern-assessment/AIML Intern assignment"



Cloning into 'ml-intern-assessment'...
remote: Enumerating objects: 246, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 246 (delta 55), reused 1 (delta 1), pack-reused 153 (from 2)
Receiving objects: 100% (246/246), 98.94 KiB | 5.21 MiB/s, done.
Resolving deltas: 100% (104/104), done.
/content/ml-intern-assessment/AIML Intern assignment/ml-intern-assessment/AIML Intern assignment/ml-intern-assessment/AIML Intern assignment


In [7]:
!ls
!ls src
!ls tests


evaluation.md  notebooks  README.md  src  tests
attention.py  utils.py
test_attention.py


In [14]:
import sys
import os

# Get the current working directory (which might be deeply nested)
current_wd = os.getcwd()

# Construct the correct absolute path to the 'src' folder relative to the current working directory
correct_src_path = os.path.join(current_wd, "src")

# Add the correct src folder to Python path if it's not already there
# Using insert(0) to prioritize this path
if correct_src_path not in sys.path:
    sys.path.insert(0, correct_src_path)

print(f"Added {correct_src_path} to sys.path.")
print(f"Current sys.path: {sys.path}")

Added /content/ml-intern-assessment/AIML Intern assignment/ml-intern-assessment/AIML Intern assignment/ml-intern-assessment/AIML Intern assignment/src to sys.path.
Current sys.path: ['/content/ml-intern-assessment/AIML Intern assignment/ml-intern-assessment/AIML Intern assignment/ml-intern-assessment/AIML Intern assignment/src', '/content', '/env/python', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '', '/usr/local/lib/python3.12/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.12/dist-packages/IPython/extensions', '/root/.ipython', '/content/ml-intern-assignment/AIML Intern assignment/src', '.']


In [15]:
import sys
sys.path.append(".")


In [16]:
from attention import scaled_dot_product_attention
print("Scaled Dot-Product Attention imported successfully!")

Scaled Dot-Product Attention imported successfully!


In [17]:
import numpy as np

# Example query, key, value matrices
Q = np.array([[[1, 0], [0, 1]]], dtype=np.float32)  # shape (1,2,2)
K = np.array([[[1, 0], [0, 1]]], dtype=np.float32)
V = np.array([[[1, 2], [3, 4]]], dtype=np.float32)

# Call function without mask
output, weights = scaled_dot_product_attention(Q, K, V, mask=None)
print("Attention Output:\n", output)
print("Attention Weights:\n", weights)


Attention Output:
 [[[1.6604769 2.660477 ]
  [2.339523  3.339523 ]]]
Attention Weights:
 [[[0.66976154 0.33023846]
  [0.33023846 0.66976154]]]


In [18]:
!pytest -q --disable-warnings --tb=short


...                                                                      [100%]
3 passed in 0.13s


In [21]:
import numpy as np
from attention import scaled_dot_product_attention
from utils import create_mask

# Example Q, K, V
Q = np.array([[[1, 0], [0, 1]]], dtype=np.float32)
K = np.array([[[1, 0], [0, 1]]], dtype=np.float32)
V = np.array([[[1, 2], [3, 4]]], dtype=np.float32)

# Without mask
out, weights = scaled_dot_product_attention(Q, K, V, mask=None)
print("Attention Output:\n", out)
print("Attention Weights:\n", weights)

# Causal mask manually (since create_mask doesn't have 'causal')
def causal_mask(size):
    mask = np.tril(np.ones((size, size), dtype=np.float32))
    return mask[None, :, :]  # add batch dimension

mask = causal_mask(Q.shape[1])
out_masked, weights_masked = scaled_dot_product_attention(Q, K, V, mask=mask)
print("Attention Output with Causal Mask:\n", out_masked)
print("Attention Weights with Causal Mask:\n", weights_masked)



Attention Output:
 [[[1.6604769 2.660477 ]
  [2.339523  3.339523 ]]]
Attention Weights:
 [[[0.66976154 0.33023846]
  [0.33023846 0.66976154]]]
Attention Output with Causal Mask:
 [[[3. 4.]
  [2. 3.]]]
Attention Weights with Causal Mask:
 [[[0.  1. ]
  [0.5 0.5]]]
